### ISSUE TITLE
Allow WiFi set up when burning micro SD card

### ISSUE THREAD

**Issue by mnishiguchi** [elixir-circuits/circuits_quickstart#101]
I just thought it would be nice if we can enable WiFi when burning micro SD card like `nerves_livebook`.
https://github.com/livebook-dev/nerves_livebook#burning-the-firmware-for-devices-that-boot-from-microsd

It seems that many newbies (including me) had issues and confusion about the USB gadget mode. While I assume most people have WiFi access, it might be difficult to judge which USB cables are compatible for the USB gadget mode.

**Comment by fhunleth** [comment]
I think this is a really good idea. Thanks for opening the issue. 

If you know how to make this change and have time, please open a PR. If not or if you're unsure, I'll add it on my next pass on `circuits_quickstart`. That will definitely be when OTP 25 is released, but might be sooner.

**Comment by mnishiguchi** [comment]
I'll start working on it hoping related code in `nerves_livebook` works here.

**Comment by fhunleth** [comment]
Included in `v0.4.15` and later.
