### ISSUE TITLE
Building the Elixir Circuits Quickstart firmware fails after mix firmware..

### ISSUE THREAD

**Issue by layeddie** [elixir-circuits/circuits_quickstart#22]
Building the Elixir Circuits Quickstart firmware fails after mix firmware..
is this a bug or something I have not configured correctly?

$ git clone https://github.com/elixir-circuits/circuits_quickstart.git
$ cd circuits_quickstart
$ export MIX_TARGET=rpi0

$ mix deps.get
$ mix firmware
.
.
.
`
|nerves_bootstrap| Building OTP Release...

* skipping runtime configuration (config/releases.exs not found)
* creating _build/rpi3_dev/rel/circuits_quickstart/releases/0.4.1/vm.args

15:18:53.506 [error] Task #PID<0.4942.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/tasks/release.ex:1300: Mix.Tasks.Release.copy/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [consolidated: "/Users/elay15/projects/nerves/circuits_quickstart/_build/rpi3_dev/lib/circuits_quickstart/consolidated"]]

15:18:53.506 [error] Task #PID<0.4944.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [:vintage_net_ethernet]]

15:18:53.506 [error] Task #PID<0.4949.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [:runtime_tools]]

15:18:53.506 [error] Task #PID<0.4945.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [:nerves_ssh]]

15:18:53.506 [error] Task #PID<0.4946.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [:circuits_i2c]]

15:18:53.506 [error] Task #PID<0.4947.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [:inets]]

15:18:53.506 [error] Task #PID<0.4948.0> started from #PID<0.94.0> terminating
** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
    (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
    (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
    (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<0.91251738/1 in Mix.Tasks.Release.assemble/1>, [:vintage_net]]
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (BadBooleanError) expected a boolean on left-side of "and", got: [keep: ["Docs"]]
        (mix 1.10.4) lib/mix/release.ex:760: anonymous fn/5 in Mix.Release.copy_ebin/3
        (elixir 1.10.4) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (mix 1.10.4) lib/mix/release.ex:756: Mix.Release.copy_ebin/3
        (mix 1.10.4) lib/mix/release.ex:727: Mix.Release.copy_app/2
        (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (elixir 1.10.4) lib/task/supervised.ex:35: Task.Supervised.reply/5
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

15:18:53~/projects/nerves/circuits_quickstart (main) 

$ elixir -v
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
16:32:10~/projects/nerves/circuits_quickstart (main) 

16:33:05~/projects/nerves/circuits_quickstart (main) 

$ mix nerves.info
==> nerves
==> circuits_quickstart

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.7.2
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.3.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.13.7
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_rpi3
  Vsn:         1.13.3
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /Users/elay15/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-1.3.2
  system:     /Users/elay15/.nerves/artifacts/nerves_system_rpi3-portable-1.13.3
  app:        /Users/elay15/projects/nerves/circuits_quickstart

|nerves_bootstrap| Loadpaths End

Nerves:           1.7.2
Nerves Bootstrap: 1.10.1
Elixir:           1.10.4
|nerves_bootstrap| Info End

16:33:17~/projects/nerves/circuits_quickstart (main) 
`

**Comment by mdsebald** [comment]
I just tried the same thing for rpi0 and rpi3, and no errors.   I'm using Elixir 1.11.2-otp-23 and Erlang 23.1.4.  I have a vague memory there was a problem with Nerves and Elixir 1.10.  I would try upgrading to 1.11 and see if that helps.

**Comment by TheEndIsNear** [comment]
I also had this issue, and resolved it by upgrading to Elixir 1.11. 

I have a different issue however, when I run ´mix firmware.burn´ I can't get the rpi0 to properly boot.

**Comment by layeddie** [comment]
I have been having problems running this on the rpi0 as well. Tried different cables, different rpi0's....
But that was with 1.10.

**Comment by fhunleth** [comment]
This looks like some change between Elixir 1.10 and 1.11's support for mix releases is affecting the project. I'm going to bump the requirement to Elixir 1.11 (see PR #23) since I don't think any of the maintainers use Elixir 1.10 any more.

If you have issues with the Circuits Quickstart, please use the officially built versions and provide more information.

**Comment by layeddie** [comment]
Now runs on my rpi0 and rpi3. Looks like this has solved my problems with rpi0 yesterday connecting via OTG cable.
$ elixir -v
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
