### ISSUE TITLE
Raspberry Pi 4 - Model B turns off after burning circuits_quickstart_rpi4.fw

### ISSUE THREAD

**Issue by iArazar** [elixir-circuits/circuits_quickstart#75]
I burned `circuits_quickstart_rpi4.fw` `v0.4.6` to "Raspberry Pi 4 - Model B" the red and green lights turn on and go off after a few seconds. I tried the previous version `0.4.5` but still, have the same issue. I tried checking using two different USB-C cables but there is no difference at all.

**Comment by fhunleth** [comment]
The Raspberry Pi 4 doesn't work when powered by USB-C on all computers since it requires a lot of power. Before doing a lot of debug, has it every worked for you on this computer. 

Another thing you can try is to power it via USB-C power supply and connect up the HDMI output to see if it does anything.

The final thing to try is to confirm that Raspberry Pi OS works fine on your board.

**Comment by iArazar** [comment]
@fhunleth 
Thank you for your help and response. 
- I've checked the connection using the USB-C power supply and USB-C, in both scenarios Raspberry Pi lights went off.
- Turned it on using a USB-C cable again, attached an HDMI cable and the Elixir console showed up on the monitor (the Raspberry Pi lights stayed off). Called some modules like `IO.inspect ("hello")` it worked properly.

---

The new issue is about the SSH connection as you said in the document `ssh circuits@nerves.local` this error occurs and is not able to connect:

`ssh: Could not resolve hostname nerves.local: Name or service not known`


Here is my Raspberry Pi network info:

![WhatsApp Image 2021-11-11 at 9 21 14 PM](https://user-images.githubusercontent.com/10072527/141345489-e5702d3b-b750-4435-ac7e-72066d9d10b0.jpeg)

**Comment by fhunleth** [comment]
From the screenshot, you're not connected to a computer via USB-C or connected to a wired Ethernet LAN or connected to WiFi. That's why you can't `ssh` to the Pi4. If you'd like to connect to WiFi, run `VintageNetWiFi.quick_configure("ssid", "password")`

**Comment by shahryarjb** [comment]
Hi @fhunleth,
This image was screenshotted when we connected and turned on the Raspberry with USB-C cable, not an adaptor!!
I am wonder how can to connect with USB-C cable, to push new code after each editing to my Raspberry.

**Comment by fhunleth** [comment]
Oh, I forget that I never updated `circuits_quickstart` to support networking over USB-C with the Pi4. You won't be able to do that for now.

**Comment by shahryarjb** [comment]
I am very appreciated, would you mind suggesting me how to update my source which is the better option in your opinion instead of updating with SD card?

**Comment by fhunleth** [comment]
Could you try the `v0.4.7` release? It supports USB gadget networking. As for other ways of updating firmware, wired Ethernet and WiFi work too.
